#generated by copilot. edit to fix and learn.
#project_access_service.py

from datetime import datetime, timezone
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models.project_access import ProjectAccess #ok maybe ill change the model names to be like this?
from app.services.audit_log_service import write_audit_log #interesting

#below is very different from the crap i made before.
    #why async?
    #why no 'class ProjectAccessService' at top?

async def get_project_access(db: AsyncSession, project_id: int) -> ProjectAccess | None:
    result = await db.execute(
        select(ProjectAccess).where(ProjectAccess.project_id == project_id)
    )
    return result.scalar_one_or_none()

async def update_project_access(
    db: AsyncSession,
    project_id: int,
    new_details: str, #used to update the details
    account_id: int,
    user_id: int,
):
    project_access = await get_project_access(db, project_id) #project_access is the row from the table, ProjectAccess is the model/blueprint itself.
    if not project_access:
        raise ValueError("ProjectAccess not found")

    old = {"access_details": project_access.access_details} #this creates a snapshot of the old value before we overwrite it.

    now = datetime.now(timezone.utc) #this solidifies the correct 'now' timing. to be used by other code for synchronocity.

    project_access.access_details = new_details
    project_access.updated_at = now
    project_access.updated_by = user_id

    await write_audit_log(
        db=db,
        entity_type="project_access",
        entity_id=project_id,
        account_id=account_id,
        performed_by=user_id,
        action="update",
        details={"old": old, "new": {"access_details": new_details}},
        performed_at=now,
    )

    await db.commit()
    await db.refresh(project_access)

    return project_access